import type { NextPage } from "next";
import Head from "next/head";
//======================================================
import i from "../styles/index.module.css";
import ii from "../styles/index2.module.css";
//======================================================
import Carousel from "../components/indexCarousel/carousel";
//======================================================
import NavBar from "../components/sideNavBar/navBar";

const Home: NextPage = () => {
  return (
    <div className={i.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={i.main}>
        <NavBar />
        <div className={i.firstCardContainer}>
          <div className={i.cards}>
            <div className={i.leftBar}>
              <div className={i.leftBarDescriptionCard}>
                <p className={i.titleLeftBar}>presontation</p>
                <p
                  className={i.p1DescriptionLeftBar}
                >{`Je suis un jeune développeur web assoiffe de connaissance
                débrouillard j’aime la musique le calme et l’esprit d’équipe`}</p>
              </div>
            </div>
            <div className={i.rightBar}></div>
          </div>
        </div>
        <div className={ii.secondCardContainer}>
          <div className={ii.cards}>
            <div className={ii.leftBar}>
              <div className={ii.underLeftBarwhiteBorder}>
                <div className={ii.learnIndoReactNextjs}>
                  <Carousel />
                </div>
              </div>
            </div>
            <div className={ii.rightBar}>
              <div className={ii.secondRightBar}>
                <p
                  className={ii.titleSecondRightBar}
                >{`Depuis le début de mon parcours en tant que développeur j'essaye de m'améliorer`}</p>
                <ul className={ii.skillsContainer}>
                  <li>React Js</li>
                  <li>Next Js</li>
                  <li>HTML / XML</li>
                  <li>CSS</li>
                  <li>Node Js</li>
                  <li>Express</li>
                  <li>MongoDB</li>
                  <li className={ii.blueThecPython}>Python</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};
export default Home;
